version: '3.9'

services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma_db_local
    volumes:
      - chroma_data:/chroma/.chroma/index
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8001:8000"

  postgres:
    image: postgres:15
    container_name: postgres_db_local
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:23
    container_name: clickhouse_local
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "9000:9000"   # TCP порт для клиента
      - "8123:8123"   # HTTP интерфейс
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1' | clickhouse-client --multiquery"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finam_hack_app_local
    command: >
      bash -c "poetry run uvicorn app_analytics.api.fast_api:create_app --host 0.0.0.0 --port 8000 --reload --no-access-log"
    volumes:
      - ./app_analytics:/app_analytics/app_analytics
      - ./alembic:/app/alembic
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      clickhouse:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finam_hack_celery_worker_local
    command: >
      bash -c "poetry run celery -A app_parsing.celery_app worker -l INFO"
    volumes:
      - ./app_parsing:/app/app_parsing
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

volumes:
  chroma_data:
    driver: local
  postgres_data:
    driver: local
  clickhouse_data:
    driver: local
